<!DOCTYPE html>
<html>
<head>
<title>Statistic Summary</title>
<style>
body { font-family: sans-serif; color: #333; }
.header { text-align: center; margin-bottom: 30px; }
.header h1 { color: #4361EE; margin-bottom: 5px; }
.section { margin-bottom: 30px; page-break-inside: avoid; }
.text-center { text-align: center; }
.chart-container { width: 100%; text-align: center; margin-bottom: 20px; }
.chart-img { width: 100%; max-width: 700px; height: auto; }
.card { border: 1px solid #e0e0e0; border-radius: 10px; padding: 20px; background-color: #fff; }
.insight-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; }
.insight-desc { font-size: 14px; line-height: 1.5; }
.stats-grid { width: 100%; margin-top: 20px; border-collapse: collapse; }
.stats-grid td { width: 33%; text-align: center; padding: 15px; border: 1px solid #eee; }
.stat-value { font-size: 24px; font-weight: bold; display: block; }
.stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
.footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; }
</style>
</head>
<body>
<div class="header">
<h1>Recalm Statistic Summary</h1>
<p>Report Date: {{ now()->format('d F Y') }} | Period: {{ ucfirst($filter) }}</p>
</div>
<!-- Chart Section -->
<div class="section">
<div class="chart-container">
@if($chartImage)
<img src="{{ $chartImage }}" class="chart-img">
@else
<p>No Graphic Available</p>
@endif
</div>
</div>
<!-- Insight Section -->
<div class="section">
<h3>Mood Insight</h3>
<div class="card text-center">
<div class="insight-title" style="color: {{ $insightColor }};">
{{ $insightTitle }}
</div>
<div class="insight-desc">
{!! $insightDesc !!}
</div>
</div>
</div>
<!-- Total Mood Counts -->
<div class="section">
<h3>Total Mood Overview</h3>
<table class="stats-grid">
<tr>
<td>
<span class="stat-value" style="color: #1E4F91;">{{ $totalSenang }}</span>
<span class="stat-label">Senang</span>
</td>
<td>
<span class="stat-value" style="color: #E69500;">{{ $totalMarah }}</span>
<span class="stat-label">Marah</span>
</td>
<td>
<span class="stat-value" style="color: #D32F2F;">{{ $totalSedih }}</span>
<span class="stat-label">Sedih</span>
</td>
</tr>
</table>
</div>
<div class="footer">
Generated by Recalm App
</div>
</body>
</html>

